version: '2'
services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: wsy123456
      MYSQL_DATABASE: wsy
      MYSQL_USER: lzt
      MYSQL_PASSWORD: lzt123456
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped
