version: '2'
services:
  mysql:
    scale: 1
    upgrade_strategy:
      start_first: true
    health_check:
      port: 3306
      interval: 2000
      timeout: 2000
      unhealthy_threshold: 3
      strategy: recreate

