version: "2"
services:
  mysql:
    scale: 1
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "root_password"
      MYSQL_DATABASE: "my_database"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "user_password"
