version: '2'
services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: always
    labels:
      io.rancher.container.pull_image: always
