version: '2'
services:
  php:
    image: php:7.4-fpm
    ports:
      - 80:80
    links:
      - mysql
      - redis
      - mq

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: yourpassword
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:alpine

  mq:
    image: rabbitmq:alpine

volumes:
  mysql_data:
