version: '2'
services:
  php:
    scale: 1
    health_check:
      port: 80
      interval: 2000
      unhealthy_threshold: 3
      healthy_threshold: 2
      response_timeout: 2000

  mysql:
    scale: 1
    health_check:
      port: 3306
      interval: 5000
      unhealthy_threshold: 3
      healthy_threshold: 2
      response_timeout: 2000

  redis:
    scale: 1
    health_check:
      port: 6379
      interval: 5000
      unhealthy_threshold: 3
      healthy_threshold: 2
      response_timeout: 2000

  mq:
    scale: 1
    health_check:
      port: 5672
      interval: 5000
      unhealthy_threshold: 3
      healthy_threshold: 2
      response_timeout: 2000

catalog:
  name: "PHP-MySQL-Redis-MQ Stack"       # 应用模板的名称
  version: "1.0.0"                       # 应用模板的版本号
  description: "A stack with PHP, MySQL, Redis, and MQ"  # 应用模板的描述
  uuid: php-mysql-redis-mq-stack         # 应用模板的 UUID，可以自定义
